### ISSUE TITLE
BUG report and solution

### ISSUE THREAD

**Issue by kodragonP** [martinez-zacharya/MOP-UP#2]
The current version can not run.
Add "subprocess.run(["mkdir", outputpath])" in line 171 of "mop-up.py" can solve.

**Comment by martinez-zacharya** [comment]
Thanks for finding this! Did you happen to see an error that looks like this?

> Traceback (most recent call last):
  File "mop-up.py", line 178, in <module>
    subprocess.run(
  File "/home/zacharymartinez/micromamba/envs/mop-up/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/zacharymartinez/micromamba/envs/mop-up/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/zacharymartinez/micromamba/envs/mop-up/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/zacharymartinez/mop-up_fix/MOP-UP/silix'

**Comment by AndAvia** [comment]
> Thanks for finding this! Did you happen to see an error that looks like this?
> 
> > Traceback (most recent call last):
> > File "mop-up.py", line 178, in 
> > subprocess.run(
> > File "/home/zacharymartinez/micromamba/envs/mop-up/lib/python3.8/subprocess.py", line 493, in run
> > with Popen(*popenargs, **kwargs) as process:
> > File "/home/zacharymartinez/micromamba/envs/mop-up/lib/python3.8/subprocess.py", line 858, in **init**
> > self._execute_child(args, executable, preexec_fn, close_fds,
> > File "/home/zacharymartinez/micromamba/envs/mop-up/lib/python3.8/subprocess.py", line 1704, in _execute_child
> > raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/zacharymartinez/mop-up_fix/MOP-UP/silix'

When I run `python3 mop-up.py my_virus_run ./final_virus.faa @ ./TestRunOutput --cpu 12` ，I'm getting this error`Traceback (most recent call last):
  File "mop-up.py", line 180, in <module>
    subprocess.run(
  File "/home/machuang/miniconda3/envs/mop-up/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/machuang/miniconda3/envs/mop-up/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/machuang/miniconda3/envs/mop-up/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/machuang/MOP-UP/silix'`,I used `chmod -R 755 silix` and still got an error.Do you know what's going on?Thank you for your answer.
